=== MiramoPDF/miramo-generic-publishing/workingFolder/helpserver_display.dtd
<!ELEMENT helpserver_display (head, (folder | topic | pdf)?)>

<!ELEMENT head (styles?, unittypes?)>

<!ELEMENT styles (styledefault?, styleoverview?)>

<!ELEMENT styledefault EMPTY>
<!ATTLIST styledefault type ( P | C ) "P"
                       level CDATA #IMPLIED
                       listtype ( none | bullet | number | text ) "none"
                       listlevel CDATA #IMPLIED
                       color CDATA #IMPLIED
                       background-color CDATA #IMPLIED
                       background-color-transparency CDATA #IMPLIED
                       fontname CDATA #IMPLIED
                       fontsize CDATA #IMPLIED
                       ul ( false | true ) "false"
                       bo ( false | true ) "false"
                       it ( false | true ) "false"
                       align ( left | right | center ) "left"
                       linespace ( 1 | 1.5 | 2 ) "1"
                       widowcontrol ( false | true ) "true"
                       keeplinestogether ( false | true ) "false"
                       keepwithnext ( false | true ) "false"
                       bordertype ( thin | thick | double ) "thin"
                       bordertop ( false | true ) "false"
                       borderbottom ( false | true ) "false"
                       borderleft ( false | true ) "false"
                       borderright ( false | true ) "false"
                       bordershadow ( false | true ) "false"
                       usepar-fontname ( false | true ) "false"
                       usepar-fontsize ( false | true ) "false"
                       usepar-fontweight ( false | true ) "false"
                       usepar-fontstyle ( false | true ) "false"
		               usepar-color ( false | true ) "false"
		               usepar-background-color ( false | true ) "false"
                       spacebefore CDATA #IMPLIED
                       spaceafter CDATA #IMPLIED
                       leftindent CDATA #IMPLIED
                       rightindent CDATA #IMPLIED>
<!ELEMENT styleoverview (styleelement*)>

<!ELEMENT styleelement EMPTY>
<!ATTLIST styleelement 
                type ( P | C ) "P"
                id CDATA #IMPLIED
                des CDATA #IMPLIED
                basestyle CDATA #IMPLIED
                nextstyle CDATA #IMPLIED
                listtype ( none | bullet | number | text ) "none"
                listlevel CDATA #IMPLIED
                color CDATA #IMPLIED
                background-color CDATA #IMPLIED
                background-color-transparency CDATA #IMPLIED
                fontname CDATA #IMPLIED
                fontsize CDATA #IMPLIED
                ul ( false | true ) "false"
                bo ( false | true ) "false"
                it ( false | true ) "false"
                align ( left | right | center ) #IMPLIED
                linespace ( 1 | 1.5 | 2 ) #IMPLIED
                widowcontrol ( false | true ) "true"
                keeplinestogether ( false | true ) "false"
                keepwithnext ( false | true ) "false"
                bordertype ( thin | thick | double ) "thin"
                bordertop ( false | true ) "false"
                borderbottom ( false | true ) "false"
                borderleft ( false | true ) "false"
                borderright ( false | true ) "false"
                bordershadow ( false | true ) "false"
                usepar-fontname ( false | true ) "false"
                usepar-fontsize ( false | true ) "false"
                usepar-fontweight ( false | true ) "false"
                usepar-fontstyle ( false | true ) "false"
                usepar-color ( false | true ) "false"
                usepar-background-color ( false | true ) "false"
                spacebefore CDATA #IMPLIED
                spaceafter CDATA #IMPLIED
                leftindent CDATA #IMPLIED
                rightindent CDATA #IMPLIED>
<!ELEMENT unittypes (unittype*)>

<!ELEMENT unittype (#PCDATA)>
<!ATTLIST unittype id CDATA #REQUIRED>

<!ELEMENT folder (title?, lines?)>
<!ATTLIST folder key CDATA #IMPLIED
                 hidedes ( false | true ) "false"
                 pointername CDATA #IMPLIED
                 resid CDATA #IMPLIED>
                 
<!ELEMENT title (#PCDATA)>

<!ELEMENT lines (folder | topic | pdf)*>

<!ELEMENT pdf (title?)>
<!ATTLIST pdf id CDATA #IMPLIED
                 hidedes ( false | true ) "false"
                 pointername CDATA #IMPLIED
                 resid CDATA #IMPLIED
                 autostart ( false | true ) "false">
                
<!ELEMENT topic (title?, units?)>
<!ATTLIST topic key CDATA #IMPLIED
                 hidedes ( false | true ) "false"
                 pointername CDATA #IMPLIED
                 resid CDATA #IMPLIED
                 autostart ( false | true ) #IMPLIED>
<!ELEMENT units (unit*)>

<!ELEMENT unit (data)>
<!ATTLIST unit type CDATA #IMPLIED>

<!ELEMENT data (par*)>

<!ELEMENT par (#PCDATA | style | br | image | select | hotspot | line | table | searchlauncher | languagelauncher | bookmark | url | file | video | audio | exit)*>
<!ATTLIST par style CDATA #IMPLIED
              align ( left | right | center ) #IMPLIED
              linespace ( 1 | 1.5 | 2 ) #IMPLIED
              spacebefore CDATA #IMPLIED
              spaceafter CDATA #IMPLIED
              leftindent CDATA #IMPLIED
              rightindent CDATA #IMPLIED
              color CDATA #IMPLIED
              background-color CDATA #IMPLIED
              fontname CDATA #IMPLIED
              fontsize CDATA #IMPLIED
              ul ( false | true ) "false"
              bo ( false | true ) "false"
              it ( false | true ) "false">

<!ELEMENT br EMPTY>

<!ELEMENT style (#PCDATA)>
<!ATTLIST style color CDATA #IMPLIED
              stylename CDATA #IMPLIED
              background-color CDATA #IMPLIED
              fontname CDATA #IMPLIED
              fontsize CDATA #IMPLIED
              ul ( false | true ) "false"
              bo ( false | true ) "false"
              it ( false | true ) "false">
              
<!ELEMENT image (imgmap?)>
<!ATTLIST image id CDATA #IMPLIED
              align ( top | bottom | left | right | middle ) #IMPLIED
              alt CDATA #IMPLIED
              width CDATA #IMPLIED
              height CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              scale CDATA #IMPLIED
              browserviewfull ( false | true ) "false"
              scaleratiobrowse CDATA #IMPLIED
              scaleratioprint CDATA #IMPLIED>
              
<!ELEMENT imgmap (imgmaparea*)>

<!ELEMENT imgmaparea (image*, url*, file*, audio*, video*, select*)>
<!ATTLIST imgmaparea shape ( rect | circ | poly ) #IMPLIED
              title CDATA #IMPLIED
              coords CDATA #IMPLIED>

<!ELEMENT select (style | image)>
<!ATTLIST select type ( I | M ) #REQUIRED
              key CDATA #REQUIRED
              actiontype ( newwindow | currentwindow | currentpane | currentfolder | dropdown | popup | block | expand ) #IMPLIED
              containername CDATA #IMPLIED
              targetpath CDATA #IMPLIED
              bookmark CDATA #IMPLIED
              viewpdf ( false | true ) "false"
              viewtype ( same | html | pdf ) "same"
              browserbars ( false | true ) "true"
              linktextupdateble ( false | true ) "true"
              hpos ( left | right | center | value ) #IMPLIED
              hposv CDATA #IMPLIED
              vpos ( top | bottom | center | value ) #IMPLIED
              vposv CDATA #IMPLIED
              height CDATA #FIXED "max"
              heightv CDATA #IMPLIED
              width CDATA #FIXED "max"
              widthv CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              activation ( autostart | linkimage | linktext ) "linktext">
              
              
<!ELEMENT hotspot EMPTY>
<!ATTLIST hotspot tag ( start | end ) #IMPLIED
              id CDATA #IMPLIED
              type ( expand  | dropdown  | popup ) "expand"
              width CDATA #IMPLIED
              height CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED>
              
<!ELEMENT hotspotinfo (data)>

<!ELEMENT bookmark (style*, image*, hotspotinfo)>
<!ATTLIST bookmark tag ( start | end ) #IMPLIED
              id CDATA #REQUIRED>
              
<!ELEMENT searchlauncher EMPTY>
<!ATTLIST searchlauncher invoketext CDATA #REQUIRED
              styleinvoke CDATA #REQUIRED
              styleentryfield CDATA #REQUIRED
              widthentryfield CDATA #REQUIRED
              folderkey CDATA #IMPLIED
              folderpathdes CDATA #IMPLIED>
              
<!ELEMENT languagelauncher EMPTY>
<!ATTLIST languagelauncher styledropdown CDATA #REQUIRED
              widthdropdown CDATA #REQUIRED
              heightdropdown CDATA #REQUIRED>
              
<!ELEMENT mail (style)>
<!ATTLIST mail to CDATA #REQUIRED>

<!ELEMENT url (style | image)>
<!ATTLIST url id CDATA #REQUIRED
              actiontype ( newwindow | currentpane  | dropdown  | popup  | embedded ) #IMPLIED
              browserbars ( false | true ) "true"
              hpos ( left | right | center | value ) #IMPLIED
              hposv CDATA #IMPLIED
              vpos ( top | bottom | center | value ) #IMPLIED
              vposv CDATA #IMPLIED
              height CDATA #FIXED "max"
              heightv CDATA #IMPLIED
              width CDATA #FIXED "max"
              widthv CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              activation ( autostart | linkimage | linktext ) "linktext">
              
<!ELEMENT file (style | image)>
<!ATTLIST file id CDATA #IMPLIED
              actiontype ( newwindow | currentpane  | dropdown  | popup  | embedded  | download ) #IMPLIED
              hpos ( left | right | center | value ) #IMPLIED
              hposv CDATA #IMPLIED
              vpos ( top | bottom | center | value ) #IMPLIED
              vposv CDATA #IMPLIED
              height CDATA #FIXED "max"
              heightv CDATA #IMPLIED
              width CDATA #FIXED "max"
              widthv CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              activation ( autostart | linkimage | linktext ) "linktext">
              
<!ELEMENT video (style | image)>
<!ATTLIST video id CDATA #IMPLIED
              actiontype ( newwindow | currentpane  | dropdown  | popup  | embedded ) #IMPLIED
              autoplay ( false | true ) "false"
              loop ( false | true ) "false"
              height CDATA #IMPLIED
              width CDATA #IMPLIED
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              activation ( autostart | linkimage | linktext ) "linktext">
              
<!ELEMENT audio (style | image)>
<!ATTLIST audio id CDATA #IMPLIED
              actiontype ( newwindow | currentpane  | dropdown  | popup  | embedded ) #IMPLIED
              autoplay ( false | true ) "false"
              loop ( false | true ) "false"
              border-color CDATA #IMPLIED
              border-size CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              margin-top CDATA #IMPLIED
              margin-bottom CDATA #IMPLIED
              margin-left CDATA #IMPLIED
              margin-right CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              activation ( autostart | linkimage | linktext ) "linktext">
              
<!ELEMENT line EMPTY>
<!ATTLIST line fill ( false | true ) "false"
              width CDATA #IMPLIED
              height CDATA #IMPLIED
              color CDATA #IMPLIED>
              
<!ELEMENT action EMPTY>
<!ATTLIST action exec ( pageskip ) #IMPLIED>
              
<!ELEMENT exit EMPTY>
<!ATTLIST exit id CDATA #REQUIRED
              parm CDATA #REQUIRED
              stylename CDATA #IMPLIED
              color CDATA #IMPLIED
              background-color CDATA #IMPLIED
              fontname CDATA #IMPLIED
              fontsize CDATA #IMPLIED
              ul ( false | true ) "false"
              bo ( false | true ) "false"
              it ( false | true ) "false">
              
<!ELEMENT table (colgroup, tr*)>
<!ATTLIST table border-size CDATA #IMPLIED
              border-color CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              valign ( top | bottom | middle ) #IMPLIED
              cellspacing CDATA #IMPLIED
              frame ( border | above | below | left | right | hsides | vsides | void ) #IMPLIED
              rules ( all | rows | cols | none ) #IMPLIED>
              
<!ELEMENT colgroup (col*)>

<!ELEMENT col EMPTY>
<!ATTLIST col width CDATA #IMPLIED>

<!ELEMENT tr (td*)>

<!ELEMENT td (data)>
<!ATTLIST td  border ( true | false ) #IMPLIED
              border-color CDATA #IMPLIED
              background-color CDATA #IMPLIED
              background-image CDATA #IMPLIED
              background-image-hpos ( left | right | center | value ) "center"
              background-image-hposv CDATA #IMPLIED
              background-image-vpos ( top | bottom | center | value ) "center"
              background-image-vposv CDATA #IMPLIED
              background-image-repeat ( no | yes | vertical | horizontal ) "no"
              background-image-color CDATA #IMPLIED
              colspan CDATA #IMPLIED
              rowspan CDATA #IMPLIED
              padding-top CDATA #IMPLIED
              padding-bottom CDATA #IMPLIED
              padding-left CDATA #IMPLIED
              padding-right CDATA #IMPLIED
              align ( left | right | center ) #IMPLIED
              valign ( top | bottom | middle ) #IMPLIED>

=== MiramoPDF/miramo-generic-publishing/workingFolder/example.xml
<?xml version='1.0' encoding='UTF-8' ?>

<!DOCTYPE helpserver_display PUBLIC "-//4ST//DTD HelpServer display 01//EN" "helpserver_display.dtd">

<helpserver_display>
  <head>
     <unittypes>
      <unittype id="G">General</unittype>
    </unittypes>

  </head>
  <folder key="BOOK    13795967172060">
    <title>LST6100 Broadcast Satellite Modem</title>
    <lines>
      <topic key="BT1368015565427" pointername="copyright">
        <title>Copyright</title>
        <units>
          <unit type="G">
            <data>
              <par style="Body Text">
                © March 11, 2022
              </par>
              <par style="Body Text">
                The material contained in this document is confidential and intended for use only by parties authorized by LogoSat Cy N.V.
              </par>
              <par style="Body Text">
                All Rights Reserved. No part of this document may be photocopied, reproduced, stored in a retrieval system, or transmitted, in any form or by any means whether, electronic, mechanical, or otherwise without the prior written permission of:
              </par>

              <par style="Body Text">
                LogoSat Cy N.V.
              </par>
              <par style="Body Text">
                Superstraat 5
              </par>
              <par style="Body Text">
                9100 Sint-Kristoff, Belgium
              </par>
              <par style="Body Text">
                tel: +32 (0)3 999 65 00
              </par>
              <par style="Body Text">
                fax: +32 (0)3 999 65 49<br/><url id="http://www.LogoSat.eu" actiontype="newwindow" activation="linktext">
                  <style stylename="Url">www.LogoSat.eu</style>
                </url> <br/><url id="mailto:sales@LogoSat.eu" actiontype="newwindow" activation="linktext">
                  <style stylename="Url">sales@LogoSat.eu</style>
                </url>
              </par>

            </data>
          </unit>
        </units>
      </topic>
      <folder key="CHAPTER 13649981147582">
        <title>EU Compliancy Statements</title>
        <lines>
          <topic key="BT1369312951175" autostart="true" hidedes="true">
            <title>To Whom It May Concern</title>
            <units>
              <unit type="G">
                <data>
                  <par style="Body Text">
                    <table rules="none">
                      <colgroup>
                        <col width="71"/>
                        <col width="535"/>
                      </colgroup>
                      <tr>
                        <td align="left" valign="middle" background-color="#FFFFFF" padding-top="5" padding-bottom="5" padding-left="5" padding-right="5">
                          <data>
                            <par style="table bodytext center">
                              <image id="imageFiles/524971/image004.png" width="36" height="36"/>
                            </par>
                          </data>
                        </td>
                        <td align="left" valign="middle" background-color="#C8C8C8" padding-top="7" padding-bottom="7" padding-left="7" padding-right="7">
                          <data>
                            <par style="Table bodytext">
                              To Whom it May Concern.
                            </par>
                          </data>
                        </td>
                      </tr>
                    </table>

                  </par>
                </data>
              </unit>
            </units>
          </topic>
          <topic key="BT13649981147583">
            <title>Radio and Telecommunications Terminal Equipment (R&amp;TTE) 5 Directive 1995/5/EC</title>
            <units>
              <unit type="G">
                <data>
                  <par style="Body Text">
                    We,
                  </par>
                  <par style="Body Text">
                    Declare that the following product:
                  </par>
                  <par style="ListBul 1">
                    Product number: LST6100
                  </par>
                  <par style="ListBul 1">
                    Type identifier: NTC/2353
                  </par>
                  <par style="Body Text">
                    to which this declaration relates is in conformity with the essential requirements of European Union Directive 1999/5/EC Radio and Telecommunication Terminal Equipment Directive Essential Requirement 3.1(a), 3.1 (b), 3.2.
                  </par>
                  <par style="Body Text">
                    Done at St-Kristoff, on March 11, 2016
                  </par>
                  <par style="Body Text">
                    <image id="imageFiles/524048/image001.png" width="130" height="91" scale="82"/>
                  </par>
                  <par style="Body Text">
                    Serge Van Herck,
                  </par>
                  <par style="Body Text">
                    CEO
                  </par>
                  <par style="Body Text">
                    LogoSat Cy N.V.
                  </par>
                  <par style="Body Text">
                    Superstraat 5 B-9100 Sint-Kristoff Belgium.
                  </par>
                  <par style="Body Text">
                    Tel: +32 (0)3 999 65 00
                  </par>
                  <par style="Body Text">
                    Fax: +32 (0)3 999 65 49
                  </par>
                </data>
              </unit>
            </units>
          </topic>
          <topic key="M61378726399990">
            <title>EMC Information</title>
            <units>
              <unit type="G">
                <data>
                  <par style="Body Text">
                    Relevant EMC information (to FCC rules)
                  </par>
                  <par style="Body Text">
                    This equipment has been tested and was found to comply with the limits for a class A digital device, pursuant to part 15 of the FCC Rules. These limits are designed to provide reasonable protection against harmful interference when the equipment is operated in a commercial environment. This equipment generates, uses and radiates radio frequency energy. If not installed and used in accordance with the instruction manual, it may cause harmful interference to radio communications.
                  </par>
                  <par style="Body Text">
                    Do not operate this equipment in a residential area, as it is likely to cause harmful interference. When this is the case, you will be required to correct the interference at your own expense.
                  </par>
                </data>
              </unit>
            </units>
          </topic>
          <topic key="BT13649981147585">
            <title>Restriction of Hazardous Substances Directive (RoHS) (Directive  2011/65/EU)</title>
            <units>
              <unit type="G">
                <data>
                  <par style="Body Text">
                    The undersigned hereby confirms the following statement:
                  </par>
                  <par style="Body Text">
                    We hereby declare that this equipment is compliant to the RoHS Directive 2011/65/EU.
                  </par>
                  <par style="Body Text">
                    Done at St-Kristoff, on March 11, 2016
                  </par>
                  <par style="Body Text">
                    <image id="imageFiles/524048/image001.png" width="130" height="91" scale="82"/>
                  </par>
                  <par style="Body Text">
                    Serge Van Herck,
                  </par>
                  <par style="Body Text">
                    CEO
                  </par>
                  <par style="Body Text">
                    LogoSat Cy N.V.
                  </par>
                  <par style="Body Text">
                    Superstraat 5 B-9100 Sint-Kristoff Belgium.
                  </par>
                  <par style="Body Text">
                    Tel: +32 (0)3 999 65 00
                  </par>
                  <par style="Body Text">
                    Fax: +32 (0)3 999 65 49
                  </par>
                </data>
              </unit>
            </units>
          </topic>
          <topic key="BT13649981147586">
            <title>Registration, Evaluation and Authorization of Chemicals (REACH)</title>
            <units>
              <unit type="G">
                <data>
                  <par style="Body Text">
                    European Regulation N°1907/2006 &quot;REACH&quot; (Registration, Evaluation, and Authorization of Chemicals), came into force on June 1st, 2007. It aims at regulating the use of the chemical substances within the European Union.
                  </par>
                  <par style="Body Text">
                    We are committed to meeting our legal obligations under REACH, as a manufacturer of articles and as a downstream user of chemicals products.
                  </par>
                  <par style="Body Text">
                    In order to comply with the REACH regulation, LogoSat Cy N.V. has put into place processes and procedures to ensure implementation and compliance with the regulation, especially the assessment of the presence of Substances of Very High Concern (SVHC&apos;s) and communication along the supply chain to both suppliers and customers.
                  </par>
                  <par style="Body Text">
